### PR TITLE
Feature/focus states

### PR DESCRIPTION
**Pull request by fraincs**
Issue:
[189](https://github.com/gsoft-inc/sg-orbit/issues/189)

### CODE REVIEW

**Comment by patricklafrance** [comment]
An active button seems to look like an focused button:

image

I am not sure this is what we want. However, if this is what we want, this seems inconsistant with a button group an active button group:

image

**Comment by patricklafrance** [comment]
Date picker calendar clear button is missing a part of the focus indicator:

image

Also true for the apply button:

image

**Comment by patricklafrance** [comment]
Seems weird that an inline date picker:

image

And a dropdown menu:

image

Are different, seems like both are some kind of underline texte with an arrow.

**Comment by patricklafrance** [comment]
A focused Select doesn't seems to have a green shadows like the other components:

image

I would expect something like a radio:

image

**Comment by patricklafrance** [comment]
I would expect the inline select to be more like the dropdown menu when focused.

We seems to have 3 different styles for basically the same thing:

Inline select:
image

Dropdown menu:
image

Inline date picker:
image

**Comment by patricklafrance** [comment]
I believe a multiple values select should support tabbing to the selected values label.

Might be out of scope for this PR but please create a new issue if this is out of scope:

image

**Comment by patricklafrance** [comment]
Transparent select focused style seems different than inline select style, is it what we want?

Transparent select:
image

Inline select:
image

**Comment by fraincs** [comment]
> An active button seems to look like a focused button:
> 
> image
> 
> I am not sure this is what we want. However, if this is what we want, this seems inconsistant with an active button group:
> 
> image

actually there is no way to do a proper active state on dark buttons, except maybe using a lighter color, a black border would not show.

**Comment by fraincs** [comment]
> > An active button seems to look like a focused button:
> > image
> > I am not sure this is what we want. However, if this is what we want, this seems inconsistant with an active button group:
> > image
> 
> actually there is no way to do a proper active state on dark buttons, except maybe using a lighter color, a black border would not show.

the other issue is that it's impossible to follow the same logic on the group button due to the way they are engineered.

**Comment by fraincs** [comment]
I removed the outline on active state, as for the group button the logic is that on active we darken the color. Since the color is white, we darken the border color. Makes sense?

**Comment by patricklafrance** [comment]
Do we want to have a different style for an hovered item and the currently "keyboard" selected item?

image

**Comment by patricklafrance** [comment]
The avatar size seems quite small, how did you choose the size?

image

**Comment by fraincs** [comment]
> The avatar size seems quite small, how did you choose the size?
> 
> image

The maximum that can fit in. Since we use the same size logic as dropdown menu.

**Comment by fraincs** [comment]
> Do we want to have a different style for an hovered item and the currently "keyboard" selected item?
> 
> image

Nothing has been set in stone with designers. I can talk to them ASAP,

**Pull request merged**
