### PR TITLE
Feature/1063

### PR DESCRIPTION
**Pull request by fraincs**
Issue: 

## Summary

Add an AlertIcon to Orbit

## What I did

Added the two sizes for the new icon

## How to test

?path=/story/icon-gallery--page

### CODE REVIEW

**Comment by alexasselin008** [comment]
This should probably affect this scenario as well? 
image

**Review by alexasselin008 — CHANGES_REQUESTED** [review]
Everything looks good, juste have to fix the Alert icon

**Review by alexasselin008 — APPROVED** [review]
Francis said the integration of the icon will be made in a new PR

**Comment by fraincs** [comment]
> 

This PR is only adding the Icon in the icons package. Another PR was ready to go for the use of the icon, I will merge the two PR in one PR.

**Pull request closed without merging**
