### PR TITLE
Rewrite dropdown menu

### PR DESCRIPTION
**Pull request by fraincs**
Issue:
[189](https://github.com/gsoft-inc/sg-orbit/issues/189) / [331](https://github.com/gsoft-inc/sg-orbit/issues/331) / [377](https://github.com/gsoft-inc/sg-orbit/issues/377) / [357](https://github.com/gsoft-inc/sg-orbit/issues/357) / [344](https://github.com/gsoft-inc/sg-orbit/issues/344) / [378](https://github.com/gsoft-inc/sg-orbit/issues/378) / [342](https://github.com/gsoft-inc/sg-orbit/issues/342)

### CODE REVIEW

**Comment by patricklafrance** [comment]
The space here seems unnecessary? Haven't looked if it's alright or not

image

Related chromatic test: https://www.chromatic.com/snapshot?appId=5d24fed056258a00204c31b6&id=5ee8ef2b8891670022ffd10e

**Comment by fraincs** [comment]
> The space here seems unnecessary? Haven't looked if it's alright or not
> 
> image
> 
> Related chromatic test: https://www.chromatic.com/snapshot?appId=5d24fed056258a00204c31b6&id=5ee8ef2b8891670022ffd10e

Not normal.

**Comment by patricklafrance** [comment]
Left padding seem weird here: 
image

http://localhost:26296/?path=/story/chromatic-button-standard--default

**Comment by patricklafrance** [comment]
Left seems problematic here:
image

http://localhost:26296/?path=/story/chromatic-button-standard--default

**Comment by patricklafrance** [comment]
A loading button should display, label, tag, etc..

image

**Comment by patricklafrance** [comment]
Without text, a compact button group have horizontal center issue:

image

http://localhost:26296/?path=/story/chromatic-buttongroup-standard--compact

**Comment by patricklafrance** [comment]
Looks like there is a problem with indertermine checkbox:

image

http://localhost:26296/?path=/story/chromatic-checkbox-indeterminate--no-text

**Comment by patricklafrance** [comment]
Here's a multiple select label value in master:

image

Here's what it looks like on this PR:

image

I personally how the buttons look in master, seems like a regression,

**Comment by fraincs** [comment]
> Here's a multiple select label value in master:
> 
> image
> 
> Here's what it looks like on this PR:
> 
> image
> 
> I personally do prefer how the buttons look in master, seems like a regression.

This is by design rounded items should half the padding of it's parent

**Comment by patricklafrance** [comment]
> > Here's a multiple select label value in master:
> > image
> > Here's what it looks like on this PR:
> > image
> > I personally do prefer how the buttons look in master, seems like a regression.
> 
> This is by design rounded items should half the padding of it's parent

Sorry, there was more context in my head than what I wrote ;)

The problem is related to the size of the label buttons not the shape of the labels

**Comment by fraincs** [comment]
> Left padding seems problematic here:
> image
> 
> http://localhost:26296/?path=/story/chromatic-button-standard--default

can you elaborate

**Comment by patricklafrance** [comment]
Seems to have a couple weird cases for a naked button:

image

http://localhost:11015/?path=/story/chromatic-button-naked--default

**Comment by patricklafrance** [comment]
How come a label in a naked button doesn't have any background?

image

http://localhost:11015/?path=/story/chromatic-button-naked--compact

**Comment by patricklafrance** [comment]
Icons are smaller is this chromatic test, not sure if this is what we want? https://www.chromatic.com/snapshot?appId=5d24fed056258a00204c31b6&id=5ee9680d5a53f400226474aa

**Comment by patricklafrance** [comment]
The buttons with a standalone icons are quite different here, not sure if this is what we want?

https://www.chromatic.com/snapshot?appId=5d24fed056258a00204c31b6&id=5ee9680d5a53f400226474b2

**Comment by patricklafrance** [comment]
> The buttons with a standalone icons are quite different here, not sure if this is what we want?
> 
> https://www.chromatic.com/snapshot?appId=5d24fed056258a00204c31b6&id=5ee9680d5a53f400226474b2

Ok found why, fix on the way.

**Comment by patricklafrance** [comment]
This one should be fix: https://www.chromatic.com/snapshot?appId=5d24fed056258a00204c31b6&id=5ee96d1201734900221957b7

**Comment by patricklafrance** [comment]
Spacing between the trigger and the menu is smaller than before: https://www.chromatic.com/snapshot?appId=5d24fed056258a00204c31b6&id=5ee96d1201734900221958d3

**Pull request merged**
