### PR TITLE
Fix Invalid Documentation Link

### PR DESCRIPTION
**Pull request by AlexandreArpin**
Issue: #219 

## What I did
Found and replaced localhost reference in documentation

## How to test
- Is this testable with Jest or Chromatic screenshots?
No
- Does this need an update to the documentation?
No

### CODE REVIEW

**Comment by AlexandreArpin** [comment]
Could you please squash your commits?

Otherwise, LGTM

**Comment by AlexandreArpin** [comment]
Dans le preview il y a des liens qui 404!

Je vais regarder ça lundi :)

**Comment by fraincs** [comment]
> Dans le preview il y a des liens qui 404! Je vais regarder ça lundi :)

@AlexandreArpin any update?

**Comment by patricklafrance** [comment]
Sorry, I fix them in my last PR, forget to reference and close this.

**Comment by AlexandreArpin** [comment]
<3 Thanks!

**Pull request closed without merging**
