### PR TITLE
Feature/dropdown semantic

### PR DESCRIPTION
**Pull request by fraincs**
Issue:
https://github.com/gsoft-inc/sg-orbit/issues/60, https://github.com/gsoft-inc/sg-orbit/issues/61, https://github.com/gsoft-inc/sg-orbit/issues/62, https://github.com/gsoft-inc/sg-orbit/issues/66

## What I did

Fixed multiple bug fixes on Semantic UI Dropdown themes

### CODE REVIEW

**Comment by patricklafrance** [comment]
The X button to clear the value of a dropdown should be consistent with our other components, it should like this:

image

View: https://sg-orbit.netlify.com/?path=/docs/components-search-input-results-set--default-story#selected-value

**Comment by patricklafrance** [comment]
I believe a "standard dropdown" should have have less emphasis when navigating through the choices.

Same issue as https://github.com/gsoft-inc/sg-orbit/issues/61 but for the "standard"

**Comment by patricklafrance** [comment]
Otherwise it's 🔥 good job!

**Comment by fraincs** [comment]
> The X button to clear the value of a dropdown should be consistent with our other components, it should look like this:
> 
> image
> 
> View: https://sg-orbit.netlify.com/?path=/docs/components-search-input-results-set--default-story#selected-value

The problem here is that clearable dropdowns are using a background image and not a button to close. This means we cannot mimic the same behaviour.

**Comment by fraincs** [comment]
> I believe a "standard dropdown" should have have less emphasis when navigating through the choices.
> 
> Same issue as #61 but for the "standard"

Since it this case it's a choice that has been made and not typing over an input, I think we should keep doing it the Semantic way : https://react.semantic-ui.com/modules/dropdown/

**Comment by patricklafrance** [comment]
> > I believe a "standard dropdown" should have have less emphasis when navigating through the choices.
> > Same issue as #61 but for the "standard"
> 
> Since it this case it's a choice that has been made and not typing over an input, I think we should keep doing it the Semantic way : https://react.semantic-ui.com/modules/dropdown/

Not sure I see the difference between this case and the searchable? Maybe in SUI react it's a bug and it's not the actual intention? Anyway, seems weird to me but if you want to keep it like this I won't block you! :)

**Comment by patricklafrance** [comment]
@fraincs do we need additional chromatic test cases for the dropdown?

**Comment by fraincs** [comment]
> @fraincs do we need additional chromatic test cases for the dropdown?

Since no new components have been added I would say no. Could we add more, probably, but this would not be linked to this story.

**Pull request merged**
