### PR TITLE
Condensed button

### PR DESCRIPTION
**Pull request by fraincs**
Issue:
- There was a need for condensed buttons.

## What I did

- Removed Pill as a shape for IconButton
- Bumped the font-size - icon size by 1up when an button is `condensed`

### CODE REVIEW

**Comment by patricklafrance** [comment]
You should merge master. Some code in this PR have been deleted from master.

**Comment by patricklafrance** [comment]
Since we do not support anymore a pill icon button. I would have expect some CSS to be deleted. Shouldn't it?

**Comment by fraincs** [comment]
Totally

Le lun. 19 oct. 2020 17 h 15, Patrick Lafrance <notifications@github.com> a
écrit :

**Comment by fraincs** [comment]
> Since we do not support anymore a pill icon button. I would have expect some CSS to be deleted. Shouldn't it?

No since there was no specific CSS for IconButton pill, it inherited the standard button CSS.

**Pull request merged**
