### PR TITLE
Add a "normalizeStyles" option to the "as" function

### PR DESCRIPTION
**Pull request by patricklafrance**
Issue: https://github.com/gsoft-inc/sg-orbit/issues/876 https://github.com/gsoft-inc/sg-orbit/issues/867

## Summary

When using the `as` function with a third party component there is currently no way to apply the default Orbit element styles to the third party component.

## What I did

My initial though was to introduce a `toOrbit(component)` function. This function would add Orbit style props capabilities and Orbit default element styles to the third party component.

From a library standpoint it seemed like a good idea. However, I don't think ShareGate have any use cases for this so it was adding useless complexity. Please correct me if I'm wrong and we do have use cases for this @LaurentDario, @alexasselin008.

The solution implemented in this PR is to extend the `as` function to accept a `normalizeStyles` option which would apply all Orbit default element styles on the resulting component.

```jsx
const NavHashLinkAsButton = as(Button, NavLink, { normalizeStyles: true });
```

This is something the `as` function could have done by default but I think most of the usage for the `as` function are only using Orbit components so I prefered to make it opt-in.

## How to test

- Is this testable with Jest or Chromatic screenshots? No

- Does this need an update to the documentation? Yes

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by patricklafrance** [comment]
@fraincs the new html elements CSS breaks the specifity because since it introduced a type selector...

So I introduced a [:where pseudo selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:where).

```
button:where(.o-ui-element) {
    background-color: transparent;
    background-image: none;
    cursor: pointer;
}
```

I don't think we care for the "Support for forgiving" so according to caniuse, it seems well supported: https://caniuse.com/?search=%3Awhere

However, the problem occurs because Orbit default element styles try to normalize all the elements. I am not sure if this is something we should be.

IMO, every elements which are not rendered by an Orbit component should use the browser default style. I don't consider a "<A>", "<Span>", "<HtmlButton>", ... Orbit components.

So I would basically remove everything from "html.css" and only keep:

```
.o-ui-element,
.o-ui-element::after,
.o-ui-element::before {
    box-sizing: border-box;
}
```

I guess there is a reason why you did this? Do you remember why?

**Comment by fraincs** [comment]
> @fraincs the new html elements CSS breaks the specifity because it introduced a type selector...
> 
> So I added a [:where pseudo selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) to reset the specifity to 0.
> 
> ```
> button:where(.o-ui-element) {
>     background-color: transparent;
>     background-image: none;
>     cursor: pointer;
> }
> ```
> 
> I don't think we care about the "forgiving" feature of `:where` so according to caniuse, it seems well supported: https://caniuse.com/?search=%3Awhere
> 
> However, the problem occurs because Orbit default elements styles try to normalize all the default element style. I am not sure if this is something Orbit should do.
> 
> IMO, every elements which are not rendered by an Orbit component should use the browser default styles. I don't consider a "A", "Span", "HtmlButton" ... Orbit components.
> 
> So I would remove everything from "html.css" and only keep:
> 
> ```
> .o-ui-element,
> .o-ui-element::after,
> .o-ui-element::before {
>     box-sizing: border-box;
> }
> ```
> 
> I guess there is a reason why you did this? Do you remember why?

More of a defensive approach, removing these would need some additional CSS in components, which I am not against, but would delay the merge.

**Comment by patricklafrance** [comment]
@fraincs got it, let's just keep this in mind that we might have an issue here.

**Comment by fraincs** [comment]
> got it, let's just keep this in mind that we might have an issue here.

By issue you mean by not removing the other normalize classes?

**Comment by patricklafrance** [comment]
@fraincs yes

**Pull request merged**
